vich_uploader:
    db_driver: orm

    mappings:
        kadry:
            uri_prefix: /dokumenty/kadry
            upload_destination: '%kernel.project_dir%/public/dokumenty/kadry'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        sprzedaz:
            uri_prefix: /dokumenty/sprzedaz
            upload_destination: '%kernel.project_dir%/public/dokumenty/sprzedaz'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer   
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        ksiegowosc:
            uri_prefix: /dokumenty/ksiegowosc
            upload_destination: '%kernel.project_dir%/public/dokumenty/ksiegowosc'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        marketing:
            uri_prefix: /dokumenty/marketing
            upload_destination: '%kernel.project_dir%/public/dokumenty/marketing'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer   
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        inne:
            uri_prefix: /dokumenty/inne
            upload_destination: '%kernel.project_dir%/public/dokumenty/inne'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
         