#index:
#    path: /
#    controller: App\Controller\DefaultController::index
homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: /admin
        permanent: true