<?php

namespace ContainerGi0Bw3C;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppAuthAuthenticatorService extends App_KernelProductionContainer
{
    /*
     * Gets the private 'App\Security\AppAuthAuthenticator' shared autowired service.
     *
     * @return \App\Security\AppAuthAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Security\\AppAuthAuthenticator'] = new \App\Security\AppAuthAuthenticator(($container->services['router'] ?? $container->getRouterService()));
    }
}
