<?php

namespace ContainerGi0Bw3C;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_Dbal_DefaultConnectionService extends App_KernelProductionContainer
{
    /*
     * Gets the public 'doctrine.dbal.default_connection' shared service.
     *
     * @return \Doctrine\DBAL\Connection
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = new \Doctrine\DBAL\Configuration();

        $b = new \Symfony\Bridge\Monolog\Logger('doctrine');
        $b->pushHandler(($container->privates['monolog.handler.null_internal'] ?? ($container->privates['monolog.handler.null_internal'] = new \Monolog\Handler\NullHandler())));

        $a->setMiddlewares([0 => new \Doctrine\DBAL\Logging\Middleware($b)]);

        return $container->services['doctrine.dbal.default_connection'] = (new \Doctrine\Bundle\DoctrineBundle\ConnectionFactory($container->parameters['doctrine.dbal.connection_factory.types']))->createConnection(['url' => $container->getEnv('resolve:DATABASE_URL'), 'driver' => 'pdo_mysql', 'host' => 'localhost', 'port' => NULL, 'user' => 'root', 'password' => NULL, 'driverOptions' => [], 'defaultTableOptions' => []], $a, new \Symfony\Bridge\Doctrine\ContainerAwareEventManager(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine.orm.default_listeners.attach_entity_listeners' => ['privates', 'doctrine.orm.default_listeners.attach_entity_listeners', 'getDoctrine_Orm_DefaultListeners_AttachEntityListenersService', true],
            'doctrine.orm.listeners.doctrine_dbal_cache_adapter_schema_subscriber' => ['privates', 'doctrine.orm.listeners.doctrine_dbal_cache_adapter_schema_subscriber', 'getDoctrine_Orm_Listeners_DoctrineDbalCacheAdapterSchemaSubscriberService', true],
            'doctrine.orm.listeners.doctrine_token_provider_schema_subscriber' => ['privates', 'doctrine.orm.listeners.doctrine_token_provider_schema_subscriber', 'getDoctrine_Orm_Listeners_DoctrineTokenProviderSchemaSubscriberService', true],
            'doctrine.orm.listeners.pdo_cache_adapter_doctrine_schema_subscriber' => ['privates', 'doctrine.orm.listeners.pdo_cache_adapter_doctrine_schema_subscriber', 'getDoctrine_Orm_Listeners_PdoCacheAdapterDoctrineSchemaSubscriberService', true],
            'vich_uploader.listener.clean.inne' => ['privates', 'vich_uploader.listener.clean.inne', 'getVichUploader_Listener_Clean_InneService', true],
            'vich_uploader.listener.clean.kadry' => ['privates', 'vich_uploader.listener.clean.kadry', 'getVichUploader_Listener_Clean_KadryService', true],
            'vich_uploader.listener.clean.ksiegowosc' => ['privates', 'vich_uploader.listener.clean.ksiegowosc', 'getVichUploader_Listener_Clean_KsiegowoscService', true],
            'vich_uploader.listener.clean.marketing' => ['privates', 'vich_uploader.listener.clean.marketing', 'getVichUploader_Listener_Clean_MarketingService', true],
            'vich_uploader.listener.clean.sprzedaz' => ['privates', 'vich_uploader.listener.clean.sprzedaz', 'getVichUploader_Listener_Clean_SprzedazService', true],
            'vich_uploader.listener.remove.inne' => ['privates', 'vich_uploader.listener.remove.inne', 'getVichUploader_Listener_Remove_InneService', true],
            'vich_uploader.listener.remove.kadry' => ['privates', 'vich_uploader.listener.remove.kadry', 'getVichUploader_Listener_Remove_KadryService', true],
            'vich_uploader.listener.remove.ksiegowosc' => ['privates', 'vich_uploader.listener.remove.ksiegowosc', 'getVichUploader_Listener_Remove_KsiegowoscService', true],
            'vich_uploader.listener.remove.marketing' => ['privates', 'vich_uploader.listener.remove.marketing', 'getVichUploader_Listener_Remove_MarketingService', true],
            'vich_uploader.listener.remove.sprzedaz' => ['privates', 'vich_uploader.listener.remove.sprzedaz', 'getVichUploader_Listener_Remove_SprzedazService', true],
            'vich_uploader.listener.upload.inne' => ['privates', 'vich_uploader.listener.upload.inne', 'getVichUploader_Listener_Upload_InneService', true],
            'vich_uploader.listener.upload.kadry' => ['privates', 'vich_uploader.listener.upload.kadry', 'getVichUploader_Listener_Upload_KadryService', true],
            'vich_uploader.listener.upload.ksiegowosc' => ['privates', 'vich_uploader.listener.upload.ksiegowosc', 'getVichUploader_Listener_Upload_KsiegowoscService', true],
            'vich_uploader.listener.upload.marketing' => ['privates', 'vich_uploader.listener.upload.marketing', 'getVichUploader_Listener_Upload_MarketingService', true],
            'vich_uploader.listener.upload.sprzedaz' => ['privates', 'vich_uploader.listener.upload.sprzedaz', 'getVichUploader_Listener_Upload_SprzedazService', true],
        ], [
            'doctrine.orm.default_listeners.attach_entity_listeners' => '?',
            'doctrine.orm.listeners.doctrine_dbal_cache_adapter_schema_subscriber' => '?',
            'doctrine.orm.listeners.doctrine_token_provider_schema_subscriber' => '?',
            'doctrine.orm.listeners.pdo_cache_adapter_doctrine_schema_subscriber' => '?',
            'vich_uploader.listener.clean.inne' => '?',
            'vich_uploader.listener.clean.kadry' => '?',
            'vich_uploader.listener.clean.ksiegowosc' => '?',
            'vich_uploader.listener.clean.marketing' => '?',
            'vich_uploader.listener.clean.sprzedaz' => '?',
            'vich_uploader.listener.remove.inne' => '?',
            'vich_uploader.listener.remove.kadry' => '?',
            'vich_uploader.listener.remove.ksiegowosc' => '?',
            'vich_uploader.listener.remove.marketing' => '?',
            'vich_uploader.listener.remove.sprzedaz' => '?',
            'vich_uploader.listener.upload.inne' => '?',
            'vich_uploader.listener.upload.kadry' => '?',
            'vich_uploader.listener.upload.ksiegowosc' => '?',
            'vich_uploader.listener.upload.marketing' => '?',
            'vich_uploader.listener.upload.sprzedaz' => '?',
        ]), [0 => 'vich_uploader.listener.clean.kadry', 1 => 'vich_uploader.listener.clean.sprzedaz', 2 => 'vich_uploader.listener.clean.ksiegowosc', 3 => 'vich_uploader.listener.clean.marketing', 4 => 'vich_uploader.listener.clean.inne', 5 => 'doctrine.orm.listeners.doctrine_dbal_cache_adapter_schema_subscriber', 6 => 'doctrine.orm.listeners.pdo_cache_adapter_doctrine_schema_subscriber', 7 => 'doctrine.orm.listeners.doctrine_token_provider_schema_subscriber', 8 => 'vich_uploader.listener.remove.kadry', 9 => 'vich_uploader.listener.upload.kadry', 10 => 'vich_uploader.listener.remove.sprzedaz', 11 => 'vich_uploader.listener.upload.sprzedaz', 12 => 'vich_uploader.listener.remove.ksiegowosc', 13 => 'vich_uploader.listener.upload.ksiegowosc', 14 => 'vich_uploader.listener.remove.marketing', 15 => 'vich_uploader.listener.upload.marketing', 16 => 'vich_uploader.listener.remove.inne', 17 => 'vich_uploader.listener.upload.inne', 18 => [0 => [0 => 'loadClassMetadata'], 1 => 'doctrine.orm.default_listeners.attach_entity_listeners']]), []);
    }
}
