<?php

namespace ContainerGi0Bw3C;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsersCrudControllerService extends App_KernelProductionContainer
{
    /*
     * Gets the public 'App\Controller\Admin\UsersCrudController' shared autowired service.
     *
     * @return \App\Controller\Admin\UsersCrudController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Admin\\UsersCrudController'] = $instance = new \App\Controller\Admin\UsersCrudController(($container->services['.container.private.security.password_encoder'] ?? $container->load('get_Container_Private_Security_PasswordEncoderService')));

        $instance->setContainer(($container->privates['.service_locator.Pq4jHMT'] ?? $container->load('get_ServiceLocator_Pq4jHMTService'))->withContext('App\\Controller\\Admin\\UsersCrudController', $container));

        return $instance;
    }
}
