<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1hs9cRH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1hs9cRH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1hs9cRH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1hs9cRH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1hs9cRH\App_KernelDevDebugContainer([
    'container.build_hash' => '1hs9cRH',
    'container.build_id' => '4585161b',
    'container.build_time' => 1653650995,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1hs9cRH');
