<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFK7mbpO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFK7mbpO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFK7mbpO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFK7mbpO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFK7mbpO\App_KernelDevDebugContainer([
    'container.build_hash' => 'FK7mbpO',
    'container.build_id' => 'e9cdfa55',
    'container.build_time' => 1649344523,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFK7mbpO');
