<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYqsvnAU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYqsvnAU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYqsvnAU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYqsvnAU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYqsvnAU\App_KernelDevDebugContainer([
    'container.build_hash' => 'YqsvnAU',
    'container.build_id' => 'ad90857d',
    'container.build_time' => 1650784562,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYqsvnAU');
